Write-Host "free-gito Help"
Write-Host "----------------"
Write-Host "Usage:"
Write-Host "  gito                Run the default template"
Write-Host "  gito <command>      Run a specific command"
Write-Host ""
Write-Host "Commands:"
Write-Host "  --help        Show this help message"
Write-Host "  --config      change settings of the default template"
Write-Host "  --version     Show the current version"
Write-Host "  ai            uses ai to create a commit message needs (wifi, time)"
Write-Host "  fast          fast and simple commit is not so percise"
